# -*- coding: utf-8 -*-
"""Untitled9.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-eNm0H8J-EpwSdO20lCLX00mPDlP66qT
"""

# -*- coding: utf-8 -*-
"""Untitled4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1DYo8YeGeGS8VCpndBWB_6esZyeni5eDV
"""

def kasalik_tashxisi(belgi):
    if belgi =="istima":
      return "parasetamol iching"
    elif belgi=="bosh og'rig'i":
      return " trimol iching"
    elif belgi=="grip ":
      return "Taylal hot iching"
    elif belgi=="tish og'rog'i":
      return "kyupen ichin"
    elif belgi=="oshqozon og'rig'i":
      return "gaviscon"
    elif belgi=="kuygan joy":
     return "Ibuprofen"
    elif belgi=="kuyish":
      return "Pantenol spreyi"
    elif belgi=="yalig'lanish":
      return "Azitromitsin"
    elif belgi=="mushaklar og'rigi":
      return "Diklofenak yoki Ibuprofen "
    else:
      return "shifokorga murojat qiling"
  belgi=input("kassalik belgisini kiriting")
  natija=kasalik_tashxisi(belgi)
  print(natija)